=== Chaste/Old-Chaste-svn-mirror/io/src/reader/SpiralParameters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="SpiralParameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SimulationDuration"/>
        <xs:element ref="SlabWidth"/>
        <xs:element ref="SlabHeight"/>
        <xs:element ref="InterNodeSpace"/>
        <xs:element ref="FaceStimulusWidth"/>
        <xs:element ref="QuadrantStimulusDelay"/>
        <xs:element ref="OutputDirectory"/>
        <xs:element ref="MeshOutputDirectory"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="SimulationDuration" type="xs:decimal"/>
  <xs:element name="SlabWidth" type="xs:decimal"/>
  <xs:element name="SlabHeight" type="xs:decimal"/>
  <xs:element name="InterNodeSpace" type="xs:decimal"/>
  <xs:element name="FaceStimulusWidth" type="xs:decimal"/>
  <xs:element name="QuadrantStimulusDelay" type="xs:decimal"/>
  <xs:element name="OutputDirectory" type="xs:NCName"/>
  <xs:element name="MeshOutputDirectory" type="xs:NCName"/>
</xs:schema>

=== Chaste/Old-Chaste-svn-mirror/io/test/data/Baseline.xml
<?xml version="1.0" encoding="UTF-8"?>
<SpiralParameters
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../src/reader/SpiralParameters.xsd">
    <SimulationDuration>10.0</SimulationDuration>
    <SlabWidth>2.0</SlabWidth>
    <SlabHeight>1.0</SlabHeight>
    <InterNodeSpace>0.25</InterNodeSpace>
    <FaceStimulusWidth>0.25</FaceStimulusWidth>
    <QuadrantStimulusDelay>1.0</QuadrantStimulusDelay>
    <OutputDirectory>SpiralWave</OutputDirectory>
    <MeshOutputDirectory>/tmp/Slab</MeshOutputDirectory>
</SpiralParameters>
