=== Chaste/Old-Chaste-svn-mirror/apps/texttest/chaste/base_bidomain/ChasteParameters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="domain_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Mono"/>
      <xs:enumeration value="Bi"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ionic_model_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BackwardEulerFoxModel2002Modified"/>
      <xs:enumeration value="BackwardEulerLuoRudyIModel1991"/>
      <xs:enumeration value="LuoRudyIModel1991OdeSystem"/>
      <xs:enumeration value="FaberRudy2000Version3Optimised"/>
      <xs:enumeration value="FaberRudy2000Version3"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="anisotropic_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Orthotropic"/>
      <xs:enumeration value="Axisymmetric"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="point_type">
    <xs:attribute name="X" type="xs:double" use="required"/>
    <xs:attribute name="Y" type="xs:double" use="required"/>
    <xs:attribute name="Z" type="xs:double" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="box_type">
    <xs:sequence>
      <xs:element name="CornerA" type="point_type"/>
      <xs:element name="CornerB" type="point_type"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="stimulus_type">
    <xs:sequence>
      <xs:element name="Strength" type="xs:double"/>
      <xs:element name="Duration" type="xs:double"/>
      <xs:element name="Delay" type="xs:double"/>
      <xs:element name="Location" type="box_type"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="cell_heterogeneity_type">
    <xs:sequence>
      <xs:element name="ScaleFactorGks" type="xs:double"/>
      <xs:element name="ScaleFactorIto" type="xs:double"/>
      <xs:element name="Location" type="box_type"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="conductivity_heterogeneity_type">
    <xs:sequence>
      <xs:element name="Longitudinal" type="xs:double"/>
      <xs:element name="Transverse" type="xs:double"/>
      <xs:element name="Normal" type="xs:double"/>
      <xs:element name="Location" type="box_type"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="slab_type">
    <xs:sequence>
      <xs:element name="SlabX" type="xs:double"/>
      <xs:element name="SlabY" type="xs:double"/>
      <xs:element name="SlabZ" type="xs:double"/>
      <xs:element name="InterNodeSpace" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="mesh_type">
  	<xs:choice>
      <xs:element name="Slab" type="slab_type"/>
      <xs:element name="LoadMesh">
      	<xs:complexType>
      		<xs:attribute name="name" type="xs:string" use="required"/>
      		<xs:attribute name="media" type="anisotropic_type" default="Orthotropic"/>
      	</xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
  
  <xs:complexType name="conductivities_type">
    <xs:attribute name="longi" type="xs:double" use="required"/>
    <xs:attribute name="trans" type="xs:double" use="required"/>
    <xs:attribute name="normal" type="xs:double" use="required"/>        
  </xs:complexType>

  <xs:complexType name="timesteps_type">
    <xs:attribute name="ode" type="xs:double" use="required"/>
    <xs:attribute name="pde" type="xs:double" use="required"/>
    <xs:attribute name="printing" type="xs:double" use="required"/>        
  </xs:complexType>

  <xs:complexType name="ksp_tolerances_type">
    <xs:attribute name="relative" type="xs:double" use="required"/>
    <xs:attribute name="absolute" type="xs:double" use="required"/>
  </xs:complexType>
  
  <xs:simpleType name="ksp_solver_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="cg"/>
      <xs:enumeration value="symmlq"/>
      <xs:enumeration value="gmres"/>      
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ksp_preconditioner_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ilu"/>
    </xs:restriction>
  </xs:simpleType>   
      
  <xs:complexType name="simulation_type">
    <xs:sequence>
      <xs:element name="SimulationDuration" type="xs:decimal"/>
      <xs:element name="Domain" type="domain_type"/>
      <xs:element name="IonicModel" type="ionic_model_type"/>
      <xs:element name="Mesh" type="mesh_type"/>
      <xs:element name="Stimulus" type="stimulus_type" maxOccurs="unbounded"/>
	  <xs:element name="CellHeterogeneity" type="cell_heterogeneity_type" minOccurs="0" maxOccurs="unbounded" />
	  <xs:element name="ConductivityHeterogeneity" type="conductivity_heterogeneity_type" minOccurs="0" maxOccurs="unbounded" />
	  <xs:element name="OutputDirectory" type="xs:string"/>
      <xs:element name="MeshOutputDirectory" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>    

  <xs:complexType name="physiological_type">
    <xs:sequence>
      <xs:element name="IntracellularConductivities" type="conductivities_type"/>
      <xs:element name="ExtracellularConductivities" type="conductivities_type" />
      <xs:element name="SurfaceAreaToVolumeRatio" type="xs:decimal"/>
      <xs:element name="Capacitance" type="xs:decimal"/>
    </xs:sequence>      
  </xs:complexType>    

  <xs:complexType name="numerical_type">
    <xs:sequence>  
  	  <xs:element name="Timesteps" type="timesteps_type"/>
      <xs:element name="KSPTolerances" type="ksp_tolerances_type"/>
      <xs:element name="KSPSolver" type="ksp_solver_type"/>
      <xs:element name="KSPPreconditioner" type="ksp_preconditioner_type"/>
    </xs:sequence>      
  </xs:complexType>    
  
  <xs:complexType name="chaste_parameters_type">
    <xs:sequence>
	  <xs:element name="Simulation" type="simulation_type"/>
	  <xs:element name="Physiological" type="physiological_type"/>
	  <xs:element name="Numerical" type="numerical_type"/>
    </xs:sequence>
  </xs:complexType>
    
  <xs:element name="ChasteParameters" type="chaste_parameters_type"/>

</xs:schema>

=== Chaste/Old-Chaste-svn-mirror/heart/test/data/ChasteParametersLoadMesh.xml
<?xml version="1.0" encoding="UTF-8"?>
<ChasteParameters
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../src/io/ChasteParameters.xsd">

	<Simulation>
		<!-- 
			Problem definition 
		-->    
	    <SimulationDuration>10.0</SimulationDuration>
	    <Domain>Mono</Domain>
	    <IonicModel>FaberRudy2000Version3</IonicModel>
	    
		<!-- 
			Mesh definition 
		-->
		<Mesh>
			<LoadMesh name="foo" conductivity_media="NoFibreOrientation"/>    
	  	</Mesh>
	
	    <!-- 
	    	Stimuli (as many <Stimulus> definitions as needed) 
	   	-->
	   	<Stimuli>
		  	<Stimulus> <!-- #1 -->
				<Strength>-25500.0</Strength>
				<Duration>0.5</Duration>
				<Delay>0</Delay>
				<Location>
					<CornerA x="-5.0" z="-5.0" y="-0.125"/>
					<CornerB x="-4.75" z="5.0" y="0.125"/>
				</Location>
			</Stimulus>	
			<Stimulus> <!-- #2 -->
				<Strength>-25500.0</Strength>
				<Duration>0.5</Duration>
				<Delay>200.0</Delay>
				<Location>
					<CornerA x="-5.0" z="-5.0" y="-0.125"/>
					<CornerB x="0.0" z="0.0" y="0.125"/>
				</Location>
			</Stimulus>
	   	</Stimuli>		
		
		<!-- 
			Output 
		-->
		<OutputDirectory>ChasteResults</OutputDirectory>
	</Simulation>
	
	<Physiological>
	    <!--
	        Conductivities
	    -->
	    <IntracellularConductivities longi="1.75" trans="1.75" normal="1.75" />
	    <ExtracellularConductivities longi="7.0"  trans="7.0"  normal="7.0" />
	    <SurfaceAreaToVolumeRatio> 1400 </SurfaceAreaToVolumeRatio>
	    <Capacitance> 1.0 </Capacitance>
	</Physiological>

	<Numerical>
		<TimeSteps ode="0.01" pde="0.01" printing="0.01"/>
		<KSPTolerances>
			<KSPRelative>1e-6</KSPRelative>
		</KSPTolerances>
		<KSPSolver>gmres</KSPSolver>
		<KSPPreconditioner>ilu</KSPPreconditioner>
	</Numerical>
</ChasteParameters>

=== Chaste/Old-Chaste-svn-mirror/apps/texttest/chaste/baseline/ChasteParameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<ChasteParameters
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="ChasteParameters.xsd">

	<!-- 
		Problem definition 
	-->    
    <SimulationDuration>4.0</SimulationDuration>
    <Domain>Mono</Domain>
    <IonicModel>BackwardEulerFoxModel2002Modified</IonicModel>
    
	<!-- 
		Mesh definition 
	-->
	<Mesh>
		<Slab>    
	    	<SlabX>5.0</SlabX>
	    	<SlabY>5.0</SlabY>
	    	<SlabZ>5.0</SlabZ>
	    	<InterNodeSpace>0.25</InterNodeSpace>
    	</Slab>
  	</Mesh>

    <!--
        Conductivities
    -->
    <IntracellularConductivities longi="1.75" trans="1.75" normal="1.75" />
    <ExtracellularConductivities longi="7.0"  trans="7.0"  normal="7.0" />
    
    <!-- 
    	Stimuli (as many <Stimulus> definitions as needed) 
   	-->
  	<Stimulus> <!-- #1 -->
		<Strength>-80000.0</Strength>
		<Duration>1.0</Duration>
		<Delay>0.0</Delay>
		<Location>
			<CornerA X="-5.0" Z="-5.0" Y="-0.125"/>
			<CornerB X="-4.50" Z="5.0" Y="0.125"/>
		</Location>
	</Stimulus>	
	<Stimulus> <!-- #2 -->
		<Strength>-80000.0</Strength>
		<Duration>1.0</Duration>
		<Delay>2.0</Delay>
		<Location>
			<CornerA X="-5.0" Z="-5.0" Y="-0.125"/>
			<CornerB X="0.0" Z="0.0" Y="0.125"/>
		</Location>
	</Stimulus>	
	
	<!-- 
		Output 
	-->
	<OutputDirectory>ChasteResults</OutputDirectory>
    <MeshOutputDirectory>Slab</MeshOutputDirectory>	
</ChasteParameters>

=== Chaste/Old-Chaste-svn-mirror/heart/test/data/Monodomain2d/monodomain2d_parameters.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<ChasteParameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/jmpf/eclipse/workspace/Chaste/heart/src/io/ChasteParameters.xsd">

  <Simulation>
    <SimulationDuration>0.100000000000000006</SimulationDuration>
    <Domain>Mono</Domain>
    <IonicModel>LuoRudyIModel1991OdeSystem</IonicModel>
    <OutputDirectory>Monodomain2d</OutputDirectory>
    <OutputFilenamePrefix>monodomain2d</OutputFilenamePrefix>
  </Simulation>

  <Physiological>
    <IntracellularConductivities longi="0.0005" normal="1.79769313486232e+308" trans="0.0005"/>
    <ExtracellularConductivities longi="7" normal="7" trans="7"/>
    <SurfaceAreaToVolumeRatio>1.000000000000000000</SurfaceAreaToVolumeRatio>
    <Capacitance>1.000000000000000000</Capacitance>
  </Physiological>

  <Numerical>
    <TimeSteps ode="0.01" pde="0.01" printing="0.01"/>
    <KSPTolerances>
      <KSPAbsolute>0.0002</KSPAbsolute>
    </KSPTolerances>
    <KSPSolver>gmres</KSPSolver>
    <KSPPreconditioner>jacobi</KSPPreconditioner>
  </Numerical>

</ChasteParameters>

=== Chaste/Old-Chaste-svn-mirror/apps/simulations/ticket671.xml
<?xml version="1.0" encoding="UTF-8"?>
<ChasteParameters
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../heart/src/io/ChasteParameters.xsd">

	<!-- 
		Problem definition 
	-->    
    <SimulationDuration>5.0</SimulationDuration>
    <Domain>Mono</Domain>
    <IonicModel>FaberRudy2000Version3</IonicModel>
    
	<!-- 
		Mesh definition 
	-->    
	<Mesh>
		<LoadMesh name="../data/upf-mesh/Cubic075mm" media="Axisymmetric"/> 
  	</Mesh>
	
    <!--
        Conductivities
    -->
    <IntracellularConductivities longi="1.75" trans="1.75" normal="1.75" />
    <ExtracellularConductivities longi="7.0"  trans="7.0"  normal="7.0" />
    
    <!-- 
    	Stimuli (as many <Stimulus> definitions as needed) 
   	-->
  	<Stimulus> <!-- #1 -->
		<Strength>-35500.0</Strength>
		<Duration>0.5</Duration>
		<Delay>0</Delay>
		<Location>
			<CornerA X="-9" Y="-5" Z="-5"/>
			<CornerB X="-8" Y="5"  Z="5"/>
		</Location>
	</Stimulus>	

	
	<!-- 
		Output 
	-->
	<OutputDirectory>Ticket671</OutputDirectory>
    <MeshOutputDirectory>Slab</MeshOutputDirectory>	
</ChasteParameters>

=== Chaste/Old-Chaste-svn-mirror/apps/texttest/chaste/base_bidomain/ChasteParameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<ChasteParameters
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="ChasteParameters.xsd">

	<!-- 
		Problem definition 
	-->    
    <SimulationDuration>4.0</SimulationDuration>
    <Domain>Bi</Domain>
    <IonicModel>BackwardEulerFoxModel2002Modified</IonicModel>
    
	<!-- 
		Mesh definition 
	-->    
    <SlabX>10.0</SlabX>
    <SlabY>0.25</SlabY>
    <SlabZ>10.0</SlabZ>
    <InterNodeSpace>0.25</InterNodeSpace>

    <!--
        Intracellular conductivities
    -->
    <LongitudinalConductivity>1.75</LongitudinalConductivity>
    <TransverseConductivity>1.75</TransverseConductivity>
    <NormalConductivity>1.75</NormalConductivity>   
    
    <!-- 
    	Stimuli (as many <Stimulus> definitions as needed) 
   	-->
  	<Stimulus> <!-- #1 -->
		<Strength>-80000.0</Strength>
		<Duration>1.0</Duration>
		<Delay>0</Delay>
		<Location>
			<CornerA X="-5.0" Z="-5.0" Y="-0.125"/>
			<CornerB X="-4.50" Z="5.0" Y="0.125"/>
		</Location>
	</Stimulus>	
	<Stimulus> <!-- #2 -->
		<Strength>-80000.0</Strength>
		<Duration>1.0</Duration>
		<Delay>2.0</Delay>
		<Location>
			<CornerA X="-5.0" Z="-5.0" Y="-0.125"/>
			<CornerB X="0.0" Z="0.0" Y="0.125"/>
		</Location>
	</Stimulus>	
	
	<!-- 
		Output 
	-->
	<OutputDirectory>ChasteResults</OutputDirectory>
    <MeshOutputDirectory>Slab</MeshOutputDirectory>	
</ChasteParameters>

=== Chaste/Old-Chaste-svn-mirror/heart/test/data/ChasteParametersSlab.xml
<?xml version="1.0" encoding="UTF-8"?>
<ChasteParameters
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../src/io/ChasteParameters.xsd">
       
	<Simulation>
		<!-- 
			Problem definition 
		-->    
	    <SimulationDuration>10.0</SimulationDuration>
	    <Domain>Mono</Domain>
	    <IonicModel>FaberRudy2000Version3</IonicModel>
	    
		<!-- 
			Mesh definition 
		-->
		<Mesh>
			<Slab>    
		    	<SlabX>4.0</SlabX>
		    	<SlabY>0.1</SlabY>
		    	<SlabZ>2.0</SlabZ>
		    	<InterNodeSpace>0.1</InterNodeSpace>
	    	</Slab>
	  	</Mesh>
	
	    <!-- 
	    	Stimuli (as many <Stimulus> definitions as needed) 
	   	-->
	  	<Stimulus> <!-- #1 -->
			<Strength>-25500.0</Strength>
			<Duration>0.5</Duration>
			<Delay>0</Delay>
			<Location>
				<CornerA X="-5.0" Z="-5.0" Y="-0.125"/>
				<CornerB X="-4.75" Z="5.0" Y="0.125"/>
			</Location>
		</Stimulus>	
		<Stimulus> <!-- #2 -->
			<Strength>-25500.0</Strength>
			<Duration>0.5</Duration>
			<Delay>200.0</Delay>
			<Location>
				<CornerA X="-5.0" Z="-5.0" Y="-0.125"/>
				<CornerB X="0.0" Z="0.0" Y="0.125"/>
			</Location>
		</Stimulus>	
		
		<!-- 
			Output 
		-->
		<OutputDirectory>ChasteResults</OutputDirectory>
	    <MeshOutputDirectory>Slab</MeshOutputDirectory>	
	</Simulation>
	
	<Physiological>
	    <!--
	        Conductivities
	    -->
	    <IntracellularConductivities longi="1.75" trans="1.75" normal="1.75" />
	    <ExtracellularConductivities longi="7.0"  trans="7.0"  normal="7.0" />
	    <SurfaceAreaToVolumeRatio> 1400 </SurfaceAreaToVolumeRatio>
	    <Capacitance> 1.0 </Capacitance>
	</Physiological>

	<Numerical>
		<Timesteps ode="0.01" pde="0.01" printing="0.01"/>
		<KSPTolerances relative="1e-6" absolute="1e-50"/>
		<KSPSolver>gmres</KSPSolver>
		<KSPPreconditioner>ilu</KSPPreconditioner>
	</Numerical>

</ChasteParameters>

=== Chaste/Old-Chaste-svn-mirror/heart/test/data/ChasteParametersFullFormat.xml
<?xml version="1.0" encoding="UTF-8"?>
<ChasteParameters
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../src/io/ChasteParameters.xsd">
       
	<Simulation>
		<!-- 
			Problem definition 
		-->    
	    <SimulationDuration>10.0</SimulationDuration>
	    <Domain>Mono</Domain>
	    <IonicModel>FaberRudy2000Version3</IonicModel>
	    
		<!-- 
			Mesh definition 
		-->
		<Mesh>
			<Slab>    
		    	<SlabX>4.0</SlabX>
		    	<SlabY>0.1</SlabY>
		    	<SlabZ>2.0</SlabZ>
		    	<InterNodeSpace>0.1</InterNodeSpace>
	    	</Slab>
	  	</Mesh>
	
	    <!-- 
	    	Stimuli (as many <Stimulus> definitions as needed) 
	   	-->
   		<Stimuli>
		  	<Stimulus> <!-- #1 -->
				<Strength>-25500.0</Strength>
				<Duration>0.5</Duration>
				<Delay>0</Delay>
				<Location>
					<CornerA x="-5.0"  y="-0.125" z="-5.0"/>
					<CornerB x="-4.75" y="0.125"  z="5.0"/>
				</Location>
			</Stimulus>	
			<Stimulus> <!-- #2 -->
				<Strength>-25500.0</Strength>
				<Duration>0.5</Duration>
				<Delay>200.0</Delay>
				<Location>
					<CornerA x="-5.0" y="-0.125" z="-5.0"/>
					<CornerB x="0.0"  y="0.125"  z="0.0"/>
				</Location>
			</Stimulus>	
		</Stimuli>

	    <!-- 
	    	Ionic cell model heterogeneities (as many <CellHeterogeneity> definitions as needed) 
	   	-->
		<CellHeterogeneities>
		  	<CellHeterogeneity> <!-- #1 -->
				<ScaleFactorGks>0.462</ScaleFactorGks>
				<ScaleFactorIto>0.0</ScaleFactorIto>
				<Location>
					<CornerA x="-2.0" y="-0.1" z="-1.0"/>
					<CornerB x="-0.5" y="0.1" z="1.0"/>
				</Location>
			</CellHeterogeneity>	
		
		  	<CellHeterogeneity> <!-- #2 -->
				<ScaleFactorGks>1.154</ScaleFactorGks>
				<ScaleFactorIto>0.85</ScaleFactorIto>
				<Location>
					<CornerA x="-0.5" y="-0.1" z="-1.0"/>
					<CornerB x="0.5" y="0.1" z="1.0"/>
				</Location>
			</CellHeterogeneity>	
		
		  	<CellHeterogeneity> <!-- #3 -->
				<ScaleFactorGks>1.154</ScaleFactorGks>
				<ScaleFactorIto>1.0</ScaleFactorIto>
				<Location>
					<CornerA x="0.5" y="-0.1" z="-1.0"/>
					<CornerB x="2.0" y="0.1" z="1.0"/>
				</Location>
			</CellHeterogeneity>
		</CellHeterogeneities>		
		
		<ConductivityHeterogeneities>
			<ConductivityHeterogeneity> <!-- #1 -->
			    <IntracellularConductivities longi="2.75" trans="2.75" normal="2.75" />
	    		<ExtracellularConductivities longi="8.0"  trans="8.0"  normal="8.0" />				
				<Location>
					<CornerA x="1.9" y="-0.1" z="-1.0"/>
					<CornerB x="2.0" y="0.1" z="1.0"/>
				</Location>				
			</ConductivityHeterogeneity>		

			<ConductivityHeterogeneity> <!-- #2 -->
			    <IntracellularConductivities longi="0.75" trans="0.75" normal="0.75" />
				<Location>
					<CornerA x="-0.1" y="-0.1" z="-1.0"/>
					<CornerB x="0.1"  y="0.1"  z="1.0"/>
				</Location>				
			</ConductivityHeterogeneity>		

			<ConductivityHeterogeneity> <!-- #3 -->
				<ExtracellularConductivities longi="8.0"  trans="8.0"  normal="8.0" />				
				<Location>
					<CornerA x="-2.0" y="-0.1" z="-1.0"/>
					<CornerB x="-1.9"  y="0.1"  z="1.0"/>
				</Location>				
			</ConductivityHeterogeneity>		
		</ConductivityHeterogeneities>		

		<!-- 
			Output 
		-->
		<OutputDirectory>ChasteResults</OutputDirectory>
	</Simulation>
	
	<Physiological>
	    <!--
	        Conductivities
	    -->
	    <IntracellularConductivities longi="1.75" trans="1.75" normal="1.75" />
	    <ExtracellularConductivities longi="7.0"  trans="7.0"  normal="7.0" />
	    <SurfaceAreaToVolumeRatio> 1400 </SurfaceAreaToVolumeRatio>
	    <Capacitance> 1.0 </Capacitance>
	</Physiological>

	<Numerical>
		<TimeSteps ode="0.025" pde="0.05" printing="1.0"/>
		<KSPTolerances>
			<KSPRelative>1e-6</KSPRelative>
		</KSPTolerances>
		<KSPSolver>gmres</KSPSolver>
		<KSPPreconditioner>ilu</KSPPreconditioner>
	</Numerical>

</ChasteParameters>
