=== Chaste/Old-Chaste-svn-mirror/heart/src/io/ChasteParameters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="domain_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Mono"/>
      <xs:enumeration value="Bi"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ionic_model_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BackwardEulerFoxModel2002Modified"/>
      <xs:enumeration value="BackwardEulerLuoRudyIModel1991"/>
      <xs:enumeration value="LuoRudyIModel1991OdeSystem"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="ChasteParameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SimulationDuration"/>
        <xs:element ref="SlabWidth"/>
        <xs:element ref="SlabHeight"/>
        <xs:element ref="InterNodeSpace"/>
        <xs:element ref="FaceStimulusWidth"/>
        <xs:element ref="QuadrantStimulusDelay"/>
        <xs:element ref="OutputDirectory"/>
        <xs:element ref="MeshOutputDirectory"/>
        <xs:element ref="Domain" />
        <xs:element ref="IonicModel" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="SimulationDuration" type="xs:decimal"/>
  <xs:element name="SlabWidth" type="xs:decimal"/>
  <xs:element name="SlabHeight" type="xs:decimal"/>
  <xs:element name="InterNodeSpace" type="xs:decimal"/>
  <xs:element name="FaceStimulusWidth" type="xs:decimal"/>
  <xs:element name="QuadrantStimulusDelay" type="xs:decimal"/>
  <xs:element name="OutputDirectory" type="xs:string"/>
  <xs:element name="MeshOutputDirectory" type="xs:string"/>
  <xs:element name="Domain" type="domain_type"/>
  <xs:element name="IonicModel" type="ionic_model_type"/>
</xs:schema>

=== Chaste/Old-Chaste-svn-mirror/ChasteParameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<ChasteParameters
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="heart/src/io/ChasteParameters.xsd">
    <SimulationDuration>10.0</SimulationDuration>
    <SlabWidth>2.0</SlabWidth>
    <SlabHeight>1.0</SlabHeight>
    <InterNodeSpace>0.25</InterNodeSpace>
    <FaceStimulusWidth>0.25</FaceStimulusWidth>
    <QuadrantStimulusDelay>1.0</QuadrantStimulusDelay>
    <OutputDirectory>ChasteResults</OutputDirectory>
    <MeshOutputDirectory>Slab</MeshOutputDirectory>
    <Domain>Bi</Domain>
    <IonicModel>LuoRudyIModel1991OdeSystem</IonicModel>
</ChasteParameters>
